appName: bidservice
dockerImageName: mahdiboudaouara/bid-management-service
imageTag: 1.0.14-4
replicaCount: 1
containerPort: 3002
containerEnvVars:
  - name: DB_HOST
    value: mysql-primary
  - name: DB_USER
    value: root
  - name: DB_PASSWORD
    value: secret-root-pwd
  - name: DB_NAME
    value: auctiondb
  - name: DB_PORT
    value: "3306"
  - name: BID_PORT
    value: "3002"
  - name: BID_SERVER
    value: "194-195-247-34.ip.linodeusercontent.com"
  - name: CLIENT_PORT
    value: "80"
  - name: CLIENT
    value: "194-195-247-34.ip.linodeusercontent.com"

servicePort: 3002
serviceType: ClusterIP
