appName: phpmyadmin
dockerImageName: phpmyadmin/phpmyadmin
replicaCount: 1
containerPort: 80
containerEnvVars:
- name: PMA_HOST
  value: "mysql-primary"
- name: PMA_ARBITRARY
  value: "1"
- name: PMA_PORT
  value: "3306"

servicePort: 80
serviceType: ClusterIP

