apiVersion: apps/v1
kind: Deployment
##metadata contains the labels spec contains selectors
metadata:
  name: {{.Values.appName}}
  labels:
    app: {{.Values.appName}}
##specification for deployment(desired not the status status inside etcd)
spec: 
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: {{.Values.appName}}
  ##spec for pod( the spec that i want (desired))
  template:
    metadata:
      labels:
        app : {{.Values.appName}}
    spec:
      imagePullSecrets:
        - name : docker-registry-key
      containers:
      - name : {{.Values.appName}}
        image: "{{.Values.dockerImageName}}:{{.Values.imageTag}}"
        imagePullPolicy: Always
        ports:  
        - containerPort: {{.Values.containerPort}}
        env:
        {{- range .Values.containerEnvVars}}
        - name: {{.name}}
          value: {{.value | quote}}
        {{- end}}
      {{- if .Values.pvcEnabled }}
      volumes:
        - name: {{.Values.volumeName}}
          persistentVolumeClaim:
            claimName: {{.Values.claimName}}
      {{- end }}
---
{{- if .Values.pvcEnabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.claimName}}
spec:
  accessModes:
    - {{.Values.volumeAccessMode}}
  resources:
    requests:
      storage: {{.Values.volumeStorage}}
  storageClassName: {{.Values.storageClassName}}
{{- end }}